//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace APIDoc.Model
{
    public class Category : BaseTitle
    {
        public Id Id { get; set; }

        public Id DomainId { get; set; }

        public Id ParentId { get; set; }

        public IList<Category> CategorySet
        {
            get;
            set;
        }

        public Category()
        {
        }

    }

}