//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace APIDocModel
{
    public class Parameter
    {
        public string Key
        {
            get;
            set;
        }

        public string Type
        {
            get;
            set;
        }

        public bool Indispensable
        {
            get;
            set;
        }

        public string Description
        {
            get;
            set;
        }

        public Parameter()
        {
        }

    }
}
