//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Response
{
	public  Set<ResponseDemo> DemoSet
	{
		get;
		set;
	}

	public  Set<Parameter> ParameterSet
	{
		get;
		set;
	}

	public  Set<ErrorCode> ErrorCodeSet
	{
		get;
		set;
	}

	public Response()
	{
	}

}

